[build]
  command = "npm run build"
  publish = ".next"

[build.processing]
  skip_processing = false

[build.environment]
  NPM_FLAGS = "--prefer-offline --no-audit"
  NEXT_PUBLIC_API_URL = "https://resume-builder-backend-o1dc.onrender.com/"
  NODE_VERSION = "18"
  PYTHON_VERSION = "3.9"

# For Next.js 13+ with App Router
[[plugins]]
  package = "@netlify/plugin-nextjs"