[build]
  command = "npm run build"
  publish = ".next"

[build.processing]
  skip_processing = false

[build.environment]
  NPM_FLAGS = "--prefer-offline --no-audit"
  NEXT_PUBLIC_API_URL = "https://resume-builder-backend-o1dc.onrender.com/"
  NODE_VERSION = "18"
  # Completely disable Python
  PYTHON_ENABLE = "false"
  # Force empty Python version to prevent any Python processing
  PYTHON_VERSION = ""


# For Next.js 13+ with App Router
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Custom plugin to set Python version
[[plugins]]
  package = "./netlify/plugins/python-version"