[build]
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://resume-builder-backend-o1dc.onrender.com/"
  NODE_VERSION = "18"

# For Next.js 13+ with App Router
[[plugins]]
  package = "@netlify/plugin-nextjs"